version: "3.0"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.11.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: kibana:8.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  data-extractor:
    container_name: data-extractor
    image: katarinaaaaa/data-extractor:latest
    environment:
      - PERIOD=$PERIOD
    volumes:
      - events:/app/storage                      
    networks:
      - es-net

  data-preprocessor:
   container_name: data-preprocessor
   image: katarinaaaaa/data-preprocessor:latest
   depends_on:
      data-extractor:
        condition: service_completed_successfully
        restart: false
   volumes:
     - events:/app/storage                      
   networks:
     - es-net

  data-loader:
   container_name: data-loader
   image: katarinaaaaa/data-loader:latest
   depends_on:
      kibana:
        condition: service_started
      data-preprocessor:
        condition: service_completed_successfully
        restart: false
   volumes:
     - events:/app/storage                      
   networks:
     - es-net

networks:
  es-net:
    driver: bridge

volumes:
  events: